[project]
name = "quantum-learning-roadmap"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "graphviz>=0.21",
    "jupyter-book==2.1.5",
    "matplotlib>=3.11.0",
    "pylatexenc==2.10",
    "python-dotenv==1.0.1",
    "qiskit-addon-cutting==0.10.0",
    "qiskit-aer==0.17.2",
    "qiskit-ibm-runtime==0.40.1",
    "qiskit-ibm-transpiler==0.13.0",
    "qiskit[visualization]==2.0.3",
]
